import assert from "node:assert/strict";
import test from "node:test";
import { Pool } from "pg";
import { getMigrations } from "better-auth/db/migration";
import { authSchemaOptions } from "../src/server/auth-options.ts";
import { database } from "../src/server/database.ts";
import { createApplication, addApplicationOrigin } from "../src/server/applications.ts";
import { closeAuthPool, createScopedAuth, resolveAuthScope, setAuthDeliveryForTests, sendEmailCode, verifyEmailCode, sessionForRequest, revokeSession, consumeRateLimit } from "../src/server/auth.ts";
import { handleKeyWayRequest } from "../src/server/http.ts";

if (process.env.npm_lifecycle_event === "test:auth:postgres" && !process.env.KEYWAY_AUTH_TEST_DATABASE_URL) {
  throw new Error("KEYWAY_AUTH_TEST_DATABASE_URL must point to a disposable PostgreSQL database");
}

test("real Better Auth endpoints: independent OTPs, application sessions, replay and renewal", { skip: !process.env.KEYWAY_AUTH_TEST_DATABASE_URL }, async (t) => {
  Object.assign(process.env, { NODE_ENV: "test" });
  process.env.DATABASE_URL = process.env.KEYWAY_AUTH_TEST_DATABASE_URL;
  process.env.BETTER_AUTH_SECRET = "disposable-auth-test-secret-01234567890123456789";
  process.env.BETTER_AUTH_URL = "http://localhost:3001";
  process.env.KEYWAY_RATE_LIMIT_SECRET = "disposable-rate-test-secret-01234567890123456789";
  process.env.KEYWAY_DASHBOARD_ORIGINS = "https://dashboard.example";
  const sql = await database();
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  await (await getMigrations(authSchemaOptions(pool))).runMigrations();
  t.after(async () => { await closeAuthPool(); await pool.end(); await sql.end(); });
  const owner = { id: crypto.randomUUID() };
  const appA = await createApplication(owner, { name: "Application A" });
  const appB = await createApplication(owner, { name: "Application B" });
  await addApplicationOrigin(owner, { appId: appA.appId, origin: "https://a.example", environment: "development" });
  await addApplicationOrigin(owner, { appId: appB.appId, origin: "https://b.example", environment: "development" });
  const emails = new Map<string, string>();
  const ipBytes = crypto.getRandomValues(new Uint8Array(2));
  const testIp = `127.3.${ipBytes[0]}.${ipBytes[1]}`;
  const dashboardIp = `127.4.${ipBytes[0]}.${ipBytes[1]}`;
  setAuthDeliveryForTests(async ({ scope, email, otp }) => { emails.set(`${scope.id}:${email}`, otp); });
  const request = (app = appA, token?: string) => new Request("http://localhost:3001/api/v1/keyway/auth/session", {
    headers: { Origin: app.appId === appA.appId ? "https://a.example" : "https://b.example", "x-keyway-app-id": app.appId, "x-keyway-client-ip": testIp, ...(token ? { Authorization: `Bearer ${token}` } : {}) },
  });
  const email = `auth-${crypto.randomUUID()}@example.com`;
  const a = await sendEmailCode(request(), email);
  const codeA = emails.get(`${appA.appId}:${email}`)!;
  const b = await sendEmailCode(request(appB), email);
  let codeB = emails.get(`${appB.appId}:${email}`)!;
  assert.ok(codeA !== codeB, "Test codes must be distinct to prove isolation");
  await assert.rejects(verifyEmailCode(request(), a.challengeId, codeB), /Incorrect/);
  await assert.rejects(verifyEmailCode(request(appB), b.challengeId, codeA), /Incorrect/);
  await assert.rejects(sendEmailCode(request(appB), email), /60 seconds/);
  await sql`update keyway_auth_challenges set created_at = now() - interval '61 seconds' where id = ${b.challengeId}`;
  const resend = await sendEmailCode(request(appB), email);
  const oldCodeB = codeB;
  codeB = emails.get(`${appB.appId}:${email}`)!;
  await assert.rejects(verifyEmailCode(request(appB), b.challengeId, oldCodeB), /Incorrect/);
  const loginA = await verifyEmailCode(request(), a.challengeId, codeA);
  const loginB = await verifyEmailCode(request(appB), resend.challengeId, codeB);
  assert.notEqual(loginA.user.id, loginB.user.id);
  await assert.rejects(sessionForRequest(request(appB, loginA.sessionToken)), /Session/);
  assert.equal((await sessionForRequest(request(appA, loginA.sessionToken))).user.id, loginA.user.id);
  await assert.rejects(verifyEmailCode(request(), a.challengeId, codeA), /Incorrect/);
  const scope = await resolveAuthScope(request());
  const instance1 = await createScopedAuth(scope);
  const instance2 = await createScopedAuth(scope);
  const concurrentEmail = `race-${crypto.randomUUID()}@example.com`;
  const challenge = await sendEmailCode(request(), concurrentEmail);
  const concurrentCode = emails.get(`${appA.appId}:${concurrentEmail}`)!;
  const nativeRequest = () => new Request("http://localhost:3001/internal-auth/sign-in/email-otp", { method: "POST", headers: { Origin: "https://a.example", "Content-Type": "application/json", "x-keyway-client-ip": testIp }, body: JSON.stringify({ email: concurrentEmail, otp: concurrentCode }) });
  const submissions = await Promise.all([instance1.handler(nativeRequest()), instance2.handler(nativeRequest())]);
  assert.equal(submissions.filter((response) => response.ok).length, 1, "Only one actual Better Auth endpoint may consume an OTP");
  assert.ok(challenge.challengeId);
  const [session] = await sql`select id, "expiresAt" from keyway_auth_sessions where "scopeId" = ${scope.id} and "userId" = (select auth_user_id from keyway_users where id = ${loginA.user.id})`;
  await sql`update keyway_auth_sessions set "updatedAt" = now() - interval '2 days', "expiresAt" = now() + interval '1 day' where id = ${session.id}`;
  const renewed = await sessionForRequest(request(appA, loginA.sessionToken));
  assert.ok(Date.parse(renewed.expiresAt) > Date.now() + 6 * 24 * 60 * 60_000);
  const dashboard = new Request("http://localhost:3001/api/v1/keyway/developer/apps", { method: "POST", headers: { Origin: "https://dashboard.example", "x-keyway-auth-scope": "dashboard", Authorization: `Bearer ${loginA.sessionToken}` }, body: JSON.stringify({ operation: "list" }) });
  assert.equal((await handleKeyWayRequest(dashboard)).status, 401);
  const dashboardRequest = (token?: string) => new Request("http://localhost:3001/api/v1/keyway/auth/session", { headers: { Origin: "https://dashboard.example", "x-keyway-auth-scope": "dashboard", "x-keyway-client-ip": dashboardIp, ...(token ? { Authorization: `Bearer ${token}` } : {}) } });
  const dashboardEmail = `developer-${crypto.randomUUID()}@example.com`;
  const dashboardChallenge = await sendEmailCode(dashboardRequest(), dashboardEmail);
  const dashboardLogin = await verifyEmailCode(dashboardRequest(), dashboardChallenge.challengeId, emails.get(`dashboard:${dashboardEmail}`)!);
  assert.equal((await sessionForRequest(dashboardRequest(dashboardLogin.sessionToken))).user.scopeId, "dashboard");
  await assert.rejects(sessionForRequest(request(appA, dashboardLogin.sessionToken)), /Session/);
  const listHeaders = new Headers(dashboard.headers);
  listHeaders.set("authorization", `Bearer ${dashboardLogin.sessionToken}`);
  const list = new Request(dashboard, { headers: listHeaders });
  const dashboardResult = await handleKeyWayRequest(list);
  assert.equal(dashboardResult.status, 200, JSON.stringify(await dashboardResult.json()));
  const dashboardWalletRequest = new Request("http://localhost:3001/api/v1/keyway/bootstrap", { method: "POST", headers: listHeaders, body: JSON.stringify({ deviceIdHash: "disposable" }) });
  assert.equal((await handleKeyWayRequest(dashboardWalletRequest)).status, 403);
  await revokeSession(request(appA, loginA.sessionToken));
  await assert.rejects(sessionForRequest(request(appA, loginA.sessionToken)), /Session/);
  const expiredEmail = `expired-${crypto.randomUUID()}@example.com`;
  const expired = await sendEmailCode(request(appB), expiredEmail);
  await sql`update keyway_auth_verifications set "expiresAt" = now() - interval '1 second' where identifier = ${`keyway:${appB.appId}:sign-in-otp-${expiredEmail}`}`;
  await assert.rejects(verifyEmailCode(request(appB), expired.challengeId, emails.get(`${appB.appId}:${expiredEmail}`)!), /Incorrect/);
  const badEmail = `attempts-${crypto.randomUUID()}@example.com`;
  const bad = await sendEmailCode(request(appB), badEmail);
  for (let i = 0; i < 5; i++) await assert.rejects(verifyEmailCode(request(appB), bad.challengeId, "000000"), /Incorrect/);
  await assert.rejects(verifyEmailCode(request(appB), bad.challengeId, emails.get(`${appB.appId}:${badEmail}`)!), /Incorrect/);
  const records = await sql`select value from keyway_auth_verifications`;
  assert.ok(records.every((row) => !/^\d{6}:/.test(row.value)), "OTP records must be hashed");
  const rateKey = `concurrent-${crypto.randomUUID()}`;
  const rates = await Promise.all(Array.from({ length: 20 }, () => consumeRateLimit(rateKey, { max: 3, window: 60 })));
  assert.equal(rates.filter((result) => result.allowed).length, 3);
  await closeAuthPool();
  assert.equal((await sessionForRequest(request(appB, loginB.sessionToken))).user.id, loginB.user.id, "Session survives a fresh auth instance");
  const [storedB] = await sql`select id from keyway_auth_sessions where "userId" = (select auth_user_id from keyway_users where id = ${loginB.user.id}) and "scopeId" = ${appB.appId}`;
  await sql`update keyway_auth_sessions set "expiresAt" = now() - interval '1 second' where id = ${storedB.id}`;
  await assert.rejects(sessionForRequest(request(appB, loginB.sessionToken)), /Session/);
  const failedEmail = `delivery-failure-${crypto.randomUUID()}@example.com`;
  setAuthDeliveryForTests(async () => { throw new Error("Disposable delivery failure"); });
  await assert.rejects(sendEmailCode(request(appA), failedEmail), /send login email/);
  const [failed] = await sql`select status from keyway_auth_challenges where scope_id = ${appA.appId} and email = ${failedEmail}`;
  assert.equal(failed.status, "failed");
  const [before] = await sql`select count(*)::int as count from keyway_auth_sessions`;
  await sql`update keyway_applications set disabled = true where app_id = ${appB.appId}`;
  await assert.rejects(sessionForRequest(request(appB, loginB.sessionToken)), /origin/);
  const [after] = await sql`select count(*)::int as count from keyway_auth_sessions`;
  assert.equal(before.count, after.count);
});
